name : disco web CD

on: 
  push: # merging is considered a push
    branches: #run CD whenever pushes are made to master
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      - run: npm install
      - run: yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.